#!/bin/sh

mbsync --config ~/.config/mbsync/mbsyncrc --all

#cd ~/.mail/email-1@gmail.com
#gmi pull

#cd ~/.mail/email-2@gmail.com
#gmi pull

#cd ~/.mail/email-3@gmail.com
#gmi pull

afew --tag --new
