#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
    # Reduce startup time slightly replace 'herbstclient "$@"' with 'cmds="$cmds , $@"' add 'herbstclient chain $cmds&' before '# find the panel'
    # Note: Do not use above command $Mod-space no longer works
}

hc emit_hook reload

# Wallpaper
xsetroot -solid '#5A8E3A'
#xwallpaper --output LVDS-1 --center ".config/herbstluftwm/Snow Leopard.jpg" --output DP-1 --center ".config/herbstluftwm/Snow Leopard.jpg"

# Terminate already running processes
killall -q polybar
killall -q redshift-gtk
killall -q redshift
killall -q clipster
killall -q greenclip
killall -q autocutsel
killall -q xbanish
pgrep -f udiskie | xargs kill -9 >/dev/null 2>&1
pgrep -f nohang | xargs kill -9 >/dev/null 2>&1

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
while pgrep -u $UID -x nohang >/dev/null; do sleep 1; done
while pgrep -u $UID -x redshift-gtk >/dev/null; do sleep 1; done
while pgrep -u $UID -x clipster >/dev/null; do sleep 1; done
while pgrep -u $UID -x greenclip >/dev/null; do sleep 1; done
while pgrep -u $UID -x autocutsel >/dev/null; do sleep 1; done
while pgrep -u $UID -x udiskie >/dev/null; do sleep 1; done
while pgrep -u $UID -x xbanish >/dev/null; do sleep 1; done

# Start programs
polybar -l info -c /home/"$USER"/.config/polybar/polybar-config herbstluftwm &
redshift-gtk &
redshift -x &
udiskie --tray &
autocutsel -fork  # Run as a daemon program in the background
autocutsel -selection PRIMARY -fork # Synchronize CLIPBOARD[default] with PRIMARY
xbanish &
clipster --daemon &
greenclip daemon &
nohang --monitor --config /usr/local/share/nohang/nohang-desktop.conf &

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close

# Monitor Switching
hc keybind $Mod-Control-1 spawn ~/.local/bin/monitor-switch.sh lvds-1
hc keybind $Mod-Control-2 spawn ~/.local/bin/monitor-switch.sh dp-1
hc keybind $Mod-Control-3 spawn ~/.local/bin/monitor-switch.sh extend

# Applications
hc keybind $Mod-Return spawn "${TERMINAL:-xterm}" # use your $TERMINAL with xterm as fallback
hc keybind $Mod-n spawn nemo
hc keybind $Mod-a spawn astroid
hc keybind $Mod-Control-z spawn ~/.config/i3/new-lock.sh
hc keybind $Mod-Shift-z spawn ~/.local/bin/lockscreen.sh
hc keybind $Mod-Control-m spawn sakura --title Micro -x micro
hc keybind $Mod-Control-s spawn sakura --title Siren -x "siren -c $HOME/.config/siren" # "~/.config/siren" --> does not work
hc keybind $Mod-Control-g spawn sakura --title Glances -x glances
hc keybind $Mod-Control-a spawn sakura --title Aerc -x aerc
hc keybind $Mod-Control-b spawn sakura --title Bower -x bower
hc keybind $Mod-Control-t spawn polybar-msg cmd restart # polybar-msg cmd [hide,show,toggle,quit]

# Volume Control
# Lenovo ThinkPad T420 volume & mute hardware buttons are non functional
hc keybind Shift-Up spawn amixer set Master 1+ # volume increase
hc keybind Shift-Down spawn amixer set Master 1- # volume decrease
hc keybind $Mod-Shift-x spawn amixer set Master toggle # mute|unmute

# herbstluftwm extras > /usr/share/doc/herbstluftwm/examples/
hc keybind $Mod-z spawn ~/.config/herbstluftwm/scripts/scratchpad.sh
hc keybind $Mod-q spawn ~/.config/herbstluftwm/scripts/q3terminal.sh
hc keybind $Mod-y spawn ~/.config/herbstluftwm/scripts/windowmenu.sh
hc keybind $Mod-t spawn ~/.config/herbstluftwm/scripts/toggledualhead.sh
hc keybind $Mod-Shift-f spawn ~/.config/herbstluftwm/scripts/floatmon.sh

# dmenu - rofi
hc keybind $Mod-Control-r spawn rofi -show
hc keybind $Mod-Control-w spawn rofi -show window
# hc keybind $Mod-Control-r spawn dmenu_extended_run
# hc keybind $Mod-Control-c spawn rofi -show calc -modi calc -no-show-match -no-sort > /dev/null

# basic movement in tiling and floating mode # focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..5} )
tag_keys=( {1..5} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-w set_layout max
hc keybind $Mod-g set_layout grid
hc keybind $Mod-v set_layout vertical
hc keybind $Mod-h set_layout horizontal

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 5
hc set frame_gap 4

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 2
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# hc set_monitors 1366x768+0+0 1920x1200+1366+0
# or simply:
#hc detect_monitors
hc set auto_detect_monitors on

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done
